# Generated by Django 3.2.23 on 2024-01-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(default='cover.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prof_pics',
            field=models.ImageField(default='prof.jpg', upload_to='images/'),
        ),
    ]
