# Generated by Django 3.2.23 on 2024-01-29 01:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240123_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(default='n1obcqp4snevd7wpmbqz', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prof_pics',
            field=cloudinary.models.CloudinaryField(default='c40te5wgb08lfd5em1pq', max_length=255, verbose_name='image'),
        ),
    ]
